#!/bin/sh
#
# This script starts all the standard applications I use.
# 
# Requires:
#   - brave
#   - gitkraken
#   - todoist
#   - pcmanfm
#   - st
#

brave & disown brave
gitkraken & disown gitkraken
todoist & disown todoist
pcmanfm & disown pcmanfm
st & disown st
