#!/bin/sh
#
# Change the background to a random image in the specified directory.
# Requires feh
#

# Check that a directory has been passed.
if [ $# -le 0 ]; then
	echo "Please specify a directory."
	exit
fi
# Randomize the image from the given directory.
feh --bg-scale --randomize $1
