#!/bin/sh
#
# Change the background to a random image in ~/Pictures/backgrounds.
#
# Requires: 
#   -feh

# Defaults.
d="$HOME/Pictures/backgrounds/"

# Check that a directory has been passed, update $d.
if [ $# -ge 1 ]; then
  d=$1
fi

# Randomize the image from the given directory.
feh --bg-scale --randomize $d
