#!/bin/sh
#
# A demnu slider for the backlight, uses udev.
# Requires: 
#   - dmenu

# Flags and variables.
backlightDir="/sys/class/backlight/intel_backlight/"	# Where the backlght values are stored.
brightnessFile="brightness"				# Where the current backlight value is stored.
maxFile="max_brightness"				# Where the max backlight value is stored.

# Read the current configurations
current="$(cat $backlightDir$brightnessFile)"		# Read the current brightness.
max="$(cat $backlightDir$maxFile)"			# Read the maximum brightness.

slider "echo <current> > $backlightDir$brightnessFile" $current $max
