#!/bin/sh
#
# Wrapper for the course tools.
#
# Requires:
#   - dmenu
#   - https://aur.archlinux.org/packages/course/
#     - course-wizzard
#     - course-select

# Defaults.
archive="$HOME/Documents/masterWorkFolder/undergraduate/"
current="$HOME/Documents/currentCourse"

if [ "$1" = "" ] || [ "$1" = "-s" ]; then
  selection=$(course-select $archive $current "" | dmenu -i)
  [ $? -ne 0 ] && exit
  course-select $archive $current $selection
fi

if [ "$1" = "-c" ]; then
  st -e course-wizard $archive
fi
