#!/bin/sh
#
# Wrapper for the course tools.
#
# Requires:
#   - dmenu
#   - https://aur.archlinux.org/packages/course/
#     - courseWizzard
#     - courseSelect

# Defaults.
archive="$HOME/Documents/masterWorkFolder/undergraduate/"
current="$HOME/Documents/currentCourse"

if [ "$1" = "" ] || [ "$1" = "-s" ]; then
  selection=$(courseSelect $archive $current -l | dmenu -i)
  if [ $? -ne 0 ]; then
    exit
  fi
  courseSelect $archive $current $selection
fi

if [ "$1" = "-c" ]; then
  st -e courseWizard $archive
fi
