#!/bin/sh
#
# Init script for nord vpn
# Requires: dmenu, openvpn
#

# Use dmenu for password prompts.
askPass() {
	echo -n $(echo "password" | dmenu -nf "#000" -nb "#000")
}

# Declare parameters.
configDir="/home/sam/repos/nord/ovpn_tcp"
pidf="/tmp/nordpid"

# Declare flags.
daemonize=0
querry=0
interactive=0

# Raise the flags.
for arg in "$@"; do
	if [ $arg = "-d" ]; then
		daemonize=1
	elif [ $arg = "-q" ]; then
		querry=1
	else
		input=$arg
	fi
done

# If the program is being run with dmenu. 
if [ $# = 0 ]; then
	daemonize=1
	interactive=1
fi

# Stop the old daemon.
if [ -e $pidf ]; then
	askPass | sudo -S kill -SIGTERM $(cat $pidf)
	if [ $? -ne 0 ]; then 
		exit
	fi
	rm $pidf
fi

# Querry for the configs.
runQuerry() {
	 ls $configDir | grep $1 | grep '.\{1,\}[1234567890]\{1,\}' -o
}

if [ $querry -ge 1 ]; then
	runQuerry $input
	exit
fi
if [ $interactive -ge 1 ]; then
	input=$(runQuerry 'nordvpn' | dmenu)
	# If we hit escape exit.
	if [ $? -ne 0 ]; then
		exit
	fi
fi
# finally start the vpn.
cd $configDir
if [ $daemonize -ge 1 ]; then
	askPass | nohup sudo -S openvpn "$configDir/$(ls $configDir | grep "$input\." | head -1)" &> /dev/null &
	if [ $? -ne 0 ]; then 
		exit
	fi
	echo $! > $pidf
else
	askPass | sudo -S openvpn "$configDir/$(ls $configDir | grep "$input\." | head -1)"
	if [ $? -ne 0 ]; then 
		exit
	fi
fi
