#!/bin/sh
#
# Access the users password vault.
#
# Requires: 
#   - pass
#   - dmenu 
#   - notify-send 
#   - xclip 
#   - xdotool
#


options=$(find .password-store/ -type f -name \*.gpg | sed 's/\.gpg//; s/.password-store\///')

selection=$(printf "$options" | dmenu -i)
[ $? -ne 0 ] && exit 1

login=$(echo $selection | awk -F'/' '{print $NF}')


k=0
while getopts ":up" opt; do
  case $opt in
    u)
      k=1
      printf "%s" $login | xclip -selection clipboard -i
      notify-send "pass" "Username coppied to clipboard"
      sleep 5
      printf "" | xclip -selection clipboard -i
      ;;
    p)
      k=1
      pass -c $selection
      [ $? -ne 0 ] && exit 1
      notify-send "pass" "Password coppied to clipboard"
      sleep 5
      printf "" | xclip -selection clipboard -i
      ;;
    \?)
      exit 1
  esac
done

if [ $k = 0 ]; then
  xdotool type $login
  xdotool key Tab
  xdotool type $(pass $selection)
fi
