#!/bin/sh
#
# Access the users password vault.
#
# Requires: 
#   - pass
#   - dmenu 
#   - notify-send 
#   - xclip 
#   - xdotool
#


options=$(find .password-store/ -type f -name \*.gpg | sed 's/\.gpg//; s/.password-store\///')

selection=$(printf "$options" | dmenu -i)
[ $? -ne 0 ] && exit 1

login=$(echo $selection | awk -F'/' '{print $NF}')

# If the user uses the --m flag
if [ "$1" = "--m" ]; then
	printf "%s" $login | xclip -selection clipboard -i
	notify-send "pass" "Username coppied to clipboard"
	sleep 5
        pass -c $selection
        notify-send "pass" "Password coppied to clipboard"
        sleep 5
        printf "" | xclip -selection clipboard -i
        exit
fi
xdotool type $login
xdotool key Tab
xdotool type $(pass $selection)
