#!/bin/sh
#
# Promodoro timer script works with status bar script.
#
# Requires: 
#   - dmenu 
#   - pomodoro

file="$HOME/.pomodoro.info"

selection=$(printf "start\nstop"|dmenu)
if [ $? -ne 0 ];then
  exit
fi

if [ "$selection" = "start" ]; then
  pomodoro_start $(pomodoro_list $file | dmenu) $file
else 
  if [ "$selection" = "stop" ]; then
    pomodoro_stop $file
  fi
fi
