#!/bin/sh
#
# A Dmenu slider for volume, backlight, ect.

if [ $# -le 2 ]; then
  # Not enough parameters.
  exit 1
fi

cmd=$1
current=$2
max=$3
currentp=$(expr 100 \* $current / $max)

inc=1 # Boolean.
while [ 1 ]; do
	if [ $inc = 1 ]; then
		in="$(printf "%s\n%s\n%s" "++" "--" $currentp | dmenu)"
	else
		in="$(printf "%s\n%s\n%s" "--" "++" $currentp | dmenu)"
	fi
	if [ "$in" = "" ]; then
		break
	fi
	if [ "$in" = "++" ]; then
		inc=1
		currentp=$(expr $currentp + 5)
	elif [ "$in" = "--" ]; then
		inc=0
		currentp=$(expr $currentp - 5)
	fi
        if [ $currentp -ge 100 ]; then
          currentp=100
        fi
        if [ $currentp -le 0 ]; then
          currentp=0
        fi
        current=$(expr $currentp \* $max / 100)
        eval "$(echo $cmd | sed "s/<current>/$current/")"
done
