#!/bin/sh

xrandr --output eDP-1 --auto
xrandr --output DP-1 --off
xrandr --output DP-3 --off

monitors="DP-3 DP-1"

for m in $monitors; do 
  bspc monitor $m -a dud
  for d in $(bspc query -D -m $m); do
    bspc desktop $d -m eDP-1
  done
done

bspc desktop eDP-1:^1 -r
~/.config/bspwm/bspwmrc
