#!/bin/sh
#
# Allow user to select a wifi profile.
#
# Requires: 
#   - netctl 
#   - dmenu

selection=$(netctl list | dmenu -i)
[ $? -ne 0 ] && exit

sudo netctl stop-all
sudo netctl start $selection
